/**
 *
 * @param Theme can be spread like {Colors, NavigationColors, Gutters, Layout, Common, ...args}
 * @return {*}
 */
export default function () {
  return {
    onBoarding: require('@/Assets/Images/on_boarding.png'),
    onBoarding2: require('@/Assets/Images/on_boarding_2.png'),
    onBoarding3: require('@/Assets/Images/on_boarding_3.png'),
    onBoarding4: require('@/Assets/Images/on_boarding_4.png'),
    onBoarding5: require('@/Assets/Images/on_boarding_5.png'),
    logo: require('@/Assets/Icons/ic_logo.png'),
    icBack: require('@/Assets/Icons/ic_back.png'),
    icIdentify: require('@/Assets/Icons/ic_identify.png'),
    icSelfieIdentify: require('@/Assets/Icons/ic_selfie_identify.png'),
    icCamera: require('@/Assets/Icons/ic_camera.png'),
    exampleSelfie: require('@/Assets/Images/example_selfie.png'),
    icCheck: require('@/Assets/Icons/ic_check.png'),
    icClose: require('@/Assets/Icons/ic_close.png'),
    bgShapeTopLeft: require('@/Assets/Images/bg_shape_top_left.png'),
    bgShapeCenterRight: require('@/Assets/Images/bg_shape_center_right.png'),
    bgShapeBottomRight: require('@/Assets/Images/bg_shape_bottom_right.png'),
    bgShapeCenter: require('@/Assets/Images/bg_shape_center.png'),
    icEmail: require('@/Assets/Icons/ic_email.png'),
    icVerification: require('@/Assets/Icons/ic_verification.png'),
    icUsername: require('@/Assets/Icons/ic_username.png'),
    icPassword: require('@/Assets/Icons/ic_password.png'),
    icInterested: require('@/Assets/Icons/ic_interested.png'),
    icRecommended: require('@/Assets/Icons/ic_recommended.png'),
    icConnectTwitter: require('@/Assets/Icons/ic_connect_twitter.png'),
    icArrowDown: require('@/Assets/Icons/ic_arrow_down.png'),
    icTwitter: require('@/Assets/Icons/ic_twitter.png'),
    icEnableNotification: require('@/Assets/Icons/ic_enable_notification.png'),
    bgNoNewNotification: require('@/Assets/Images/bg_no_new_notification.png'),
    icArrow: require('@/Assets/Icons/ic_arrow.png'),

    icLogin: require('@/Assets/Icons/ic_login.png'),
    icEyeShow: require('@/Assets/Icons/ic_eye_show.png'),

    icLogoBg: require('@/Assets/Icons/ic_logo_bg.png'),

    icTabHome: require('@/Assets/Icons/ic_tab_home.png'),
    icTabHomeFocused: require('@/Assets/Icons/ic_tab_home_focused.png'),
    icTabMessage: require('@/Assets/Icons/ic_tab_message.png'),
    icTabMesaageFocused: require('@/Assets/Icons/ic_tab_mesaage_focused.png'),
    icTabNotification: require('@/Assets/Icons/ic_tab_notification.png'),
    icTabNotificationFocused: require('@/Assets/Icons/ic_tab_notification_focused.png'),
    icTabChallenge: require('@/Assets/Icons/ic_tab_challenge.png'),
    icTabChallengeFocused: require('@/Assets/Icons/ic_tab_challenge_focused.png'),

    bgTab: require('@/Assets/Images/bg_tab.png'),




    icActionSetting: require('@/Assets/Icons/ic_action_setting.png'),
    icMessage: require('@/Assets/Icons/ic_message.png'),
    icSearch: require('@/Assets/Icons/ic_search.png'),

    icActionSearch: require('@/Assets/Icons/ic_action_search.png'),
    icActionCalendar: require('@/Assets/Icons/ic_action_calendar.png'),

    icBroadcast: require('@/Assets/Icons/ic_broadcast.png'),
    icActionOption: require('@/Assets/Icons/ic_action_option.png'),
    icPerson: require('@/Assets/Icons/ic_person.png'),
    icTagMessage: require('@/Assets/Icons/ic_tag_message.png'),

    icActionCalendarAdd: require('@/Assets/Icons/ic_action_calendar_add.png'),
    icActionSearchBg: require('@/Assets/Icons/ic_action_search_bg.png'),
    icClock: require('@/Assets/Icons/ic_clock.png'),
    icCalendar: require('@/Assets/Icons/ic_calendar.png'),
    icActionOptionMore: require('@/Assets/Icons/ic_action_option_more.png'),

    icAttachment: require('@/Assets/Icons/ic_attachment.png'),
    icMicrophone: require('@/Assets/Icons/ic_microphone.png'),
    icEmoji: require('@/Assets/Icons/ic_emoji.png'),
    icVerified: require('@/Assets/Icons/ic_verified.png'),
    icSend: require('@/Assets/Icons/ic_send.png'),
    icEmptySearch: require('@/Assets/Icons/ic_empty_search.png'),
    icActionPlus: require('@/Assets/Icons/ic_action_plus.png'),
    icActionEmoji: require('@/Assets/Icons/ic_action_emoji.png'),

    icWorld: require('@/Assets/Icons/ic_world.png'),
    icLock: require('@/Assets/Icons/ic_lock.png'),
    icChatRoom: require('@/Assets/Icons/ic_chat_room.png'),
    icChatRoomSmall: require('@/Assets/Icons/ic_chat_room_small.png'),

    icHamburger: require('@/Assets/Icons/ic_hamburger.png'),
    icAddProfile: require('@/Assets/Icons/ic_add_profile.png'),
    icPlus: require('@/Assets/Icons/ic_plus.png'),
    icChatRoomLock: require('@/Assets/Icons/ic_chat_room_lock.png'),
    icRules: require('@/Assets/Icons/ic_rules.png'),
    icAnnouncement: require('@/Assets/Icons/ic_announcement.png'),
    icLogoDark: require('@/Assets/Icons/ic_logo_dark.png'),
    ic2Person: require('@/Assets/Icons/ic_2_person.png'),
    icAddProfile2: require('@/Assets/Icons/ic_add_profile_2.png'),
    icNotification: require('@/Assets/Icons/ic_notification.png'),
    icSetting: require('@/Assets/Icons/ic_setting.png'),
    icActionShare: require('@/Assets/Icons/ic_action_share.png'),
    icActionCopyLink: require('@/Assets/Icons/ic_action_copy_link.png'),
    icActionWhatsapp: require('@/Assets/Icons/ic_action_whatsapp.png'),
    icActionFbMessenger: require('@/Assets/Icons/ic_action_fb_messenger.png'),
    icActionGmail: require('@/Assets/Icons/ic_action_gmail.png'),
    icLocation: require('@/Assets/Icons/ic_location.png'),
    icActionShareGray: require('@/Assets/Icons/ic_action_share_gray.png'),
    icCheck2: require('@/Assets/Icons/ic_check_2.png'),
    icEmptyEvent: require('@/Assets/Icons/ic_empty_event.png'),
    icArrowDown2: require('@/Assets/Icons/ic_arrow_down_2.png'),
    icVolume: require('@/Assets/Icons/ic_volume.png'),
    icEdit2: require('@/Assets/Icons/ic_edit_2.png'),
    icActionNotification: require('@/Assets/Icons/ic_action_notification.png'),

    // Drawer Left
    icStrokeGradient: require('@/Assets/Icons/ic_stroke_gradient.png'),
    icGradientCircle: require('@/Assets/Icons/ic_gradient_circle.png'),
    icWaivlength: require('@/Assets/Icons/ic_waivlength.png'),
    icMessagesTab: require('@/Assets/Icons/ic_messages_tab.png'),
    icAddTab: require('@/Assets/Icons/ic_add_tab.png'),
    icCircleTab1506: require('@/Assets/Icons/ic_circle_tab_1506.png'),
    icCircleTab1507: require('@/Assets/Icons/ic_circle_tab_1507.png'),

    // Drawer Right
    icInviteDrawerRight: require('@/Assets/Icons/ic_invite_drawer_right.png'),
    icSettingDrawerRight: require('@/Assets/Icons/ic_setting_drawer_right.png'),
    icPinDrawerRight: require('@/Assets/Icons/ic_pin_drawer_right.png'),
    icNotificationDrawerRight: require('@/Assets/Icons/ic_notification_drawer_right.png'),
    icCheckBot: require('@/Assets/Icons/ic_check_bot.png'),

    icClose2: require('@/Assets/Icons/ic_close_2.png'),
    icLocation2: require('@/Assets/Icons/ic_location_2.png'),
    icInfo: require('@/Assets/Icons/ic_info.png'),
    icModeration: require('@/Assets/Icons/ic_moderation.png'),
    icChannel: require('@/Assets/Icons/ic_channel.png'),
    icRules2: require('@/Assets/Icons/ic_rules_2.png'),
    icBan: require('@/Assets/Icons/ic_ban.png'),
    icEdit: require('@/Assets/Icons/ic_edit.png'),

    // Home Tab
    icThreeDotVertical: require('@/Assets/Icons/ic_three_dot_vertical.png'),
    icLikeHomeTabSmall: require('@/Assets/Icons/ic_like_home_tab_small.png'),
    icCommentHomeTabSmall: require('@/Assets/Icons/ic_comment_home_tab_small.png'),
    icShareHomeTabSmall: require('@/Assets/Icons/ic_share_home_tab_small.png'),
    icBookmarkHomeTabSmall: require('@/Assets/Icons/ic_bookmark_home_tab_small.png'),
    icEmojiHomeTab: require('@/Assets/Icons/ic_emoji_home_tab.png'),
    icHeartHomeTab: require('@/Assets/Icons/ic_heart_home_tab.png'),
    icBookOpen: require('@/Assets/Icons/ic_book_open.png'),

    // Notification Tab
    icNotificationSetting: require('@/Assets/Icons/ic_notification_setting.png'),
    icHorizontalThreeDot: require('@/Assets/Icons/ic_horizontal_three_dot.png'),

    // Challenge Tab
    icDartboardChallenge: require('@/Assets/Icons/ic_dartboard_challenge.png'),
    icLevelChallenge: require('@/Assets/Icons/ic_level_challenge.png'),
    icBgChallengeItem: require('@/Assets/Icons/ic_bg_challenge_item.png'),
    icChallengeItemPurple: require('@/Assets/Icons/ic_challenge_item_purple.png'),
    icProgressBarChallenge: require('@/Assets/Icons/ic_progress_bar_challenge.png'),
    icCrownChallenge: require('@/Assets/Icons/ic_crown_challenge.png'),
    icWaivlengthWhite: require('@/Assets/Icons/ic_waivlength_white.png'),
    icPlusChallenge: require('@/Assets/Icons/ic_plus_challenge.png'),
    icImportChallenge: require('@/Assets/Icons/ic_import_challenge.png'),
    icPrestigeLevelChallenge: require('@/Assets/Icons/ic_prestige_level_challenge.png'),
    icRewardsCollected: require('@/Assets/Icons/ic_rewards_collected.png'),

    // Wallet
    icShieldSecurity: require('@/Assets/Icons/ic_shield_security.png'),

    // DeFi detail
    icGroup1DefiDetail: require('@/Assets/Icons/ic_group_1_defi_detail.png'),
    icGroup2DefiDetail: require('@/Assets/Icons/ic_group_2_defi_detail.png'),
    icGroup3DefiDetail: require('@/Assets/Icons/ic_group_3_defi_detail.png'),
    icGroup4DefiDetail: require('@/Assets/Icons/ic_group_4_defi_detail.png'),
    icAddWalletDefiDetail: require('@/Assets/Icons/ic_add_wallet_defi_detail.png'),
    icCardPurpleBgDefi: require('@/Assets/Images/ic_card_purple_bg_defi.png'),
    icEditWhite: require('@/Assets/Icons/ic_edit_white.png'),
    icBxNetworkChart: require('@/Assets/Icons/ic_bx_network_chart.png'),
    icCopyWallet: require('@/Assets/Icons/ic_copy_wallet.png'),
    icArrowDownWallet: require('@/Assets/Icons/ic_arrow_down_wallet.png'),
    icClaimDefi: require('@/Assets/Icons/ic_claim_defi.png'),
    icRepeat: require('@/Assets/Icons/ic_repeat.png'),
    icDollar: require('@/Assets/Icons/ic_dollar.png'),
    icArrowSelectCoin: require('@/Assets/Icons/ic_arrow_select_coin.png'),
    icArrowTimeCoin: require('@/Assets/Icons/ic_arrow_time_coin.png'),
    icNiceEthereumLogo: require('@/Assets/Icons/ic_nice_ethereum_logo.png'),
    icTagWallet: require('@/Assets/Icons/ic_tag_wallet.png'),
    icSendWallet: require('@/Assets/Icons/ic_send_wallet.png'),
    icReceiveWallet: require('@/Assets/Icons/ic_receive_wallet.png'),
    icAlertCircle: require('@/Assets/Icons/ic_alert_circle.png'),
    icExportWallet: require('@/Assets/Icons/ic_export_wallet.png'),
    icSettingsSendWallet: require('@/Assets/Icons/ic_settings_send_wallet.png'),
    icCopySendWallet: require('@/Assets/Icons/ic_copy_send_wallet.png'),
    icScanSendWallet: require('@/Assets/Icons/ic_scan_send_wallet.png'),
    icCryptocurrencyEth: require('@/Assets/Icons/ic_cryptocurrency_eth.png'),
    icPolygonSendWallet: require('@/Assets/Icons/ic_polygon_send_wallet.png'),
    icSendWhiteWallet: require('@/Assets/Icons/ic_send_white_wallet.png'),
    icAddCustomToken: require('@/Assets/Icons/ic_add_custom_token.png'),
    icVerifyListedToken: require('@/Assets/Icons/ic_verify_listed_token.png'),
    icEmojioneQuestionMark: require('@/Assets/Icons/ic_emojione_question_mark.png'),
    icVerifyGreen: require('@/Assets/Icons/ic_verify_green.png'),
    icIntersectSeasonPass: require('@/Assets/Icons/ic_intersect_season_pass.png'),
    icBackWhite: require('@/Assets/Icons/ic_back_white.png'),
    icCameraSwitch: require('@/Assets/Icons/ic_camera_switch.png'),
    icQrscanLeftTop: require('@/Assets/Icons/ic_qrscan_left_top.png'),
    icQrscanRightTop: require('@/Assets/Icons/ic_qrscan_right_top.png'),
    icQrscanLeftBottom: require('@/Assets/Icons/ic_qrscan_left_bottom.png'),
    icQrscanRightBottom: require('@/Assets/Icons/ic_qrscan_right_bottom.png'),
    icFeather: require('@/Assets/Icons/ic_feather.png'),
    icWhiteBackProfile: require('@/Assets/Icons/ic_white_back_profile.png'),
    icWhiteHorizontalDot: require('@/Assets/Icons/ic_white_horizontal_dot.png'),
    icMessage36: require('@/Assets/Icons/ic_message_36.png'),
    icNotVerify: require('@/Assets/Icons/ic_not_verify.png'),
    icAttachment14: require('@/Assets/Icons/ic_attachment_14.png'),
    icCalender14: require('@/Assets/Icons/ic_calender_14.png'),
    icGallery: require('@/Assets/Icons/ic_gallery.png'),
    icGifNewPost: require('@/Assets/Icons/ic_gif_new_post.png'),
    icAlignLeft: require('@/Assets/Icons/ic_align_left.png'),
    icLocationNewPost: require('@/Assets/Icons/ic_location_new_post.png'),
    icGlobalNewPost: require('@/Assets/Icons/ic_global_new_post.png'),
    icArrowRightMenu: require('@/Assets/Icons/ic_arrow_right_menu.png'),
    icProfileMenu: require('@/Assets/Icons/ic_profile_menu.png'),
    icMonetizationMenu: require('@/Assets/Icons/ic_monetization_menu.png'),
    icInviteFriendMenu: require('@/Assets/Icons/ic_invite_friend_menu.png'),
    icBriefcase: require('@/Assets/Icons/ic_briefcase.png'),
    icSettingPink: require('@/Assets/Icons/ic_setting_pink.png'),
    icReferAFriend: require('@/Assets/Images/ic_refer_a_friend.png'),
    icDollarCircle: require('@/Assets/Icons/ic_dollar_circle.png'),
    icProfileAdd: require('@/Assets/Icons/ic_profile_add.png'),
    icChatroomArrowRight: require('@/Assets/Icons/ic_chatroom_arrow_right.png'),
    icUserChatVerified: require('@/Assets/Icons/ic_user_chat_verified.png'),
    icUserChatNotVerified: require('@/Assets/Icons/ic_user_chat_not_verified.png'),
    icAdminRole: require('@/Assets/Icons/ic_admin_role.png'),
    icBansBg: require('@/Assets/Images/ic_bans_bg.png'),
    icProfileRole: require('@/Assets/Icons/ic_profile_role.png'),
    icMoreCircle: require('@/Assets/Icons/ic_more_circle.png'),
    icEyedropper: require('@/Assets/Icons/ic_eyedropper.png'),
    
    // Dialog Asset Tile
    icBinanceCoin: require('@/Assets/Icons/ic_binance_coin.png'),
    icArrowSwapHorizontal: require('@/Assets/Icons/ic_arrow_swap_horizontal.png'),
    icSend20: require('@/Assets/Icons/ic_send_20.png'),
    icSendHistory: require('@/Assets/Icons/ic_send_history.png'),
    icReceivedHistory: require('@/Assets/Icons/ic_received_history.png'),
    // Dialog History Tile
    icReceivedHistoryTile: require('@/Assets/Icons/ic_received_history_tile.png'),
    icCopyHistoryTile: require('@/Assets/Icons/ic_copy_history_tile.png'),
    icGlobalHistoryTile: require('@/Assets/Icons/ic_global_history_tile.png'),

    icHelpCircle: require('@/Assets/Icons/ic_help_circle.png'),
    icCryptocurrencyBnb: require('@/Assets/Icons/ic_cryptocurrency_bnb.png'),
    icArrowDownConfirmSwap: require('@/Assets/Icons/ic_arrow_down_confirm_swap.png'),
    icCryptocurrencyUsdt: require('@/Assets/Icons/ic_cryptocurrency_usdt.png'),
    icHashtag: require('@/Assets/Icons/ic_hashtag.png'),
    icCopyBlue: require('@/Assets/Icons/ic_copy_blue.png'),
    icExternalLink: require('@/Assets/Icons/ic_external_link.png'),
    icChevronDown: require('@/Assets/Icons/ic_chevron_down.png'),
    icArrowDownRemoveLiquidity: require('@/Assets/Icons/ic_arrow_down_remove_liquidity.png'),

  }
}
