

export const EVENTS = {
    OPEN_CREATE_AUDIO_ROOM_DIALOG: "OPEN_CREATE_AUDIO_ROOM_DIALOG",
    OPEN_GROUP_CONVERSATION_OPTION_DIALOG: "OPEN_GROUP_CONVERSATION_OPTION_DIALOG",
    OPEN_GROUP_CONVERSATION_INVITE_DIALOG: "OPEN_GROUP_CONVERSATION_INVITE_DIALOG",
    OPEN_GROUP_CONVERSATION_EVENT_DIALOG: "OPEN_GROUP_CONVERSATION_EVENT_DIALOG",
}

