

export const EVENTS = {
    OPEN_CREATE_AUDIO_ROOM_DIALOG: "OPEN_CREATE_AUDIO_ROOM_DIALOG",
    OPEN_GROUP_CONVERSATION_OPTION_DIALOG: "OPEN_GROUP_CONVERSATION_OPTION_DIALOG",
    OPEN_GROUP_CONVERSATION_INVITE_DIALOG: "OPEN_GROUP_CONVERSATION_INVITE_DIALOG",
    OPEN_GROUP_CONVERSATION_EVENT_DIALOG: "OPEN_GROUP_CONVERSATION_EVENT_DIALOG",
    OPEN_GROUP_CONVERSATION_NOTIFICATION_DIALOG: "OPEN_GROUP_CONVERSATION_NOTIFICATION_DIALOG",
    OPEN_GROUP_CONVERSATION_LEAVE_GROUP_DIALOG: "OPEN_GROUP_CONVERSATION_LEAVE_GROUP_DIALOG",
    OPEN_ADD_WALLET_DIALOG: "OPEN_ADD_WALLET_DIALOG",
    OPEN_RENAME_WALLET_DIALOG: "OPEN_RENAME_WALLET_DIALOG",
    OPEN_ASSET_TILE_WALLET_DIALOG: "OPEN_ASSET_TILE_WALLET_DIALOG",
    OPEN_HISTORY_TILE_WALLET_DIALOG: "OPEN_HISTORY_TILE_WALLET_DIALOG",
    OPEN_EXCHANGE_SETTING_DIALOG: "OPEN_EXCHANGE_SETTING_DIALOG",
    OPEN_SELECT_TOKEN_DIALOG: "OPEN_SELECT_TOKEN_DIALOG",
    OPEN_CONFIRM_SWAP_STEP1_DIALOG: "OPEN_CONFIRM_SWAP_STEP1_DIALOG",
    OPEN_CONFIRM_SWAP_STEP2_DIALOG: "OPEN_CONFIRM_SWAP_STEP2_DIALOG",
    OPEN_FIND_OTHER_LP_TOKEN_DIALOG: "OPEN_FIND_OTHER_LP_TOKEN_DIALOG",
    OPEN_ADD_LIQUIDITY_DIALOG: "OPEN_ADD_LIQUIDITY_DIALOG",
    OPEN_CONFIRM_ADD_LIQUIDITY_DIALOG: "OPEN_CONFIRM_ADD_LIQUIDITY_DIALOG",
    OPEN_REMOVE_LIQUIDITY_DIALOG: "OPEN_REMOVE_LIQUIDITY_DIALOG",
    OPEN_ADD_MEMBER_ROLE_DIALOG: "OPEN_ADD_MEMBER_ROLE_DIALOG",
    OPEN_MANAGE_CHANNEL_ACCESS_DIALOG: "OPEN_MANAGE_CHANNEL_ACCESS_DIALOG",
    OPEN_PICK_ROLE_COLOUR_DIALOG: "OPEN_PICK_ROLE_COLOUR_DIALOG",
    OPEN_DELETE_ROLE_DIALOG: "OPEN_DELETE_ROLE_DIALOG",
    OPEN_ADD_MEMBERS_DIALOG: "OPEN_ADD_MEMBERS_DIALOG",
}

